Ds 276 add nl searching keywords to scraper
mondu-ai/mondu-website-scrapper pull request #5
Opened 2022-08-23 13:14 UTC by metanouvelle

1. automate the process of clean and dedup on given urls.
2. automate the process of applying hyperlink formula within scraper for the purpose of url validating.
3. add definition of B2B for NL

2022-08-23 13:41 UTC, jmunar reviewed
Looks good to me, except for some style and documentation issues. Please go through them

2022-08-23 13:41 UTC, jmunar commented on mondu_website_scrapper/__init__.py
> +sys.dont_write_bytecode = True
This looks like a very random statement, some comment about why it's here would help

2022-08-23 13:41 UTC, jmunar commented on mondu_website_scrapper/gsheet_api/read_from_gsheet.py
> +    spreadsheet_name: str = None
dataclass has a way to define default values without using `__post_init__`, but something like:

```python
from dataclasses import Field

class CleanReadFromGsheet:
    ...
    spreadsheet_name: str = Field(default=SPREADSHEET_NAME)
```

2022-08-23 13:41 UTC, jmunar commented on mondu_website_scrapper/gsheet_api/read_from_gsheet.py
>      Returns: a dataframe
A class doesn't actually return anything, unless you define the `__call__` method. You should describe how to use the class in the docstring

2022-08-23 17:40 UTC, rodrigoazs requested changes

2022-08-23 17:40 UTC, rodrigoazs commented on mondu_website_scrapper/gsheet_api/read_from_gsheet.py
> +            get_value_from_column.append(i[self.url_input_col])
Use list comprehension:

`get_value_from_column = [i[self.url_input_col] for i in self.input_worksheet.get_all_records()]`

2022-08-23 17:40 UTC, rodrigoazs commented on mondu_website_scrapper/gsheet_api/read_from_gsheet.py
> +                '=HYPERLINK("' + value + '","' + "applied_hyperlink_func" + '")'
Use f-strings. Pylint and flake8 are not being run on this code?

2022-08-24 11:36 UTC, jmunar commented on mondu_website_scrapper/spiders/catch_fish_scraper.py
> +        keyword = "thuiswinke"
Is it `thuiswinke` and not `thuiswinkel` on purpose?

2022-08-24 11:36 UTC, jmunar commented on mondu_website_scrapper/spiders/catch_fish_scraper.py
> +    def _extract_thuiswinkel_certificate(self, response: scrapy.http.response) -> list:
It is bad architecture to have a configuration file setting the parameters for each country, and at the same time having country-specific logic here. The usual solution is to subclass for each country, adding the specific bits. I think it's fine for now, but I would recommend to add decoupling this to the webscraper roadmap

2022-08-24 11:52 UTC, metanouvelle commented on mondu_website_scrapper/spiders/catch_fish_scraper.py
> +    def _extract_thuiswinkel_certificate(self, response: scrapy.http.response) -> list:
let us discuss it through a call

2022-08-24 11:52 UTC, metanouvelle commented on mondu_website_scrapper/spiders/catch_fish_scraper.py
> +        keyword = "thuiswinke"
typo

2022-08-24 11:53 UTC, metanouvelle commented on mondu_website_scrapper/spiders/catch_fish_scraper.py
> +        keyword = "thuiswinke"
fixed

2022-08-24 11:55 UTC, jmunar approved these changes

2022-08-24 12:00 UTC, metanouvelle commented on mondu_website_scrapper/gsheet_api/read_from_gsheet.py
> +            get_value_from_column.append(i[self.url_input_col])
fixed

2022-08-24 12:00 UTC, metanouvelle commented on mondu_website_scrapper/gsheet_api/read_from_gsheet.py
> +                '=HYPERLINK("' + value + '","' + "applied_hyperlink_func" + '")'
fixed

2022-08-26 09:03 UTC, merged